/* This takes the cleaned ENIGH tables and joins them into a single
 * semantic table */
CREATE TABLE semantic_schema.semantic_table AS

/* Union the household expenses, personal expenses, and personal incomes
 * to the "transaction" level. */
SELECT * FROM
(SELECT folioviv,
	foliohog,
	NULL AS numren,
	'household_expense' AS transaction_level,
	clave as transaction_type,
	cantidad,
	NULL AS colegia,
	costo,
	fecha_adqu,
	fecha_pago,
	forma_pago,
	NULL AS frec_rem,
	frecuencia,
	gas_nm_tri,
	gasto,
	gasto_nm,
	gasto_tri,
	imujer_tri,
	inmujer,
	NULL AS inscrip,
	NULL AS inst,
	inst_1,
	inst_2,
	lugar_comp,
	NULL AS material,
	mes_dia,
	num_meses,
	num_pagos,
	orga_inst,
	pago_mp,
	tipo_gasto,
	ultim_pago,
	NULL AS mes_1,
	NULL AS mes_2,
	NULL AS mes_3,
	NULL AS mes_4,
	NULL AS mes_5,
	NULL AS mes_6,
	CAST(NULL AS NUMERIC) AS ing_1,
	CAST(NULL AS NUMERIC) AS ing_2,
	CAST(NULL AS NUMERIC) AS ing_3,
	CAST(NULL AS NUMERIC) AS ing_4,
	CAST(NULL AS NUMERIC) AS ing_5,
	CAST(NULL AS NUMERIC) AS ing_6,
	CAST(NULL AS NUMERIC) AS ing_tri
	FROM clean.enigh_gastohogar

UNION ALL
SELECT folioviv,
       foliohog,
       numren,
       'personal_expense' AS transaction_level,
       clave AS transaction_type,
       cantidad,
       colegia,
       costo,
       NULL AS fecha_adqu,
       NULL AS fecha_pago,
       forma_pago,
       frec_rem,
       NULL AS frecuencia,
       gas_nm_tri,
       gasto,
       gasto_nm,
       gasto_tri,
       NULL AS imujer_tri,
       NULL AS inmujer,
       inscrip,
       inst,
       NULL AS inst_1,
       NULL AS inst_2,
       NULL AS lugar_comp,
       material,
       mes_dia,
       NULL AS num_meses,
       NULL AS num_pagos,
       NULL AS orga_inst,
       NULL AS pago_mp,
       tipo_gasto,
       NULL AS ultim_pago,
       NULL AS mes_1,
       NULL AS mes_2,
       NULL AS mes_3,
       NULL AS mes_4,
       NULL AS mes_5,
       NULL AS mes_6,
       CAST(NULL AS NUMERIC) AS ing_1,
       CAST(NULL AS NUMERIC) AS ing_2,
       CAST(NULL AS NUMERIC) AS ing_3,
       CAST(NULL AS NUMERIC) AS ing_4,
       CAST(NULL AS NUMERIC) AS ing_5,
       CAST(NULL AS NUMERIC) AS ing_6,
       CAST(NULL AS NUMERIC) AS ing_tri
FROM clean.enigh_gastopersona

UNION ALL
SELECT folioviv,
       foliohog,
       numren,
       'personal_income' AS transaction_level,
       clave as transaction_type,
       NULL AS cantidad,
       NULL AS colegia,
       NULL AS costo,
       NULL AS fecha_adqu,
       NULL AS fecha_pago,
       NULL AS forma_pago,
       NULL AS frec_rem,
       NULL AS frecuencia,
       NULL AS gas_nm_tri,
       NULL AS gasto,
       NULL AS gasto_nm,
       NULL AS gasto_tri,
       NULL AS imujer_tri,
       NULL AS inmujer,
       NULL AS inscrip,
       NULL AS inst,
       NULL AS inst_1,
       NULL AS inst_2,
       NULL AS lugar_comp,
       NULL AS material,
       NULL AS mes_dia,
       NULL AS num_meses,
       NULL AS num_pagos,
       NULL AS orga_inst,
       NULL AS pago_mp,
       NULL AS tipo_gasto,
       NULL AS ultim_pago,
       mes_1,
       mes_2,
       mes_3,
       mes_4,
       mes_5,
       mes_6,
       ing_1,
       ing_2,
       ing_3,
       ing_4,
       ing_5,
       ing_6,
       ing_tri
FROM clean.enigh_ingresos) transactions

/* Join with person level demographic information */
FULL JOIN

(SELECT folioviv,
	foliohog,
	numren,
	parentesco AS poblacion_parentesco,
	sexo AS poblacion_sexo,
	edad AS poblacion_edad,
	madre_hog AS poblacion_madre_hog,
	madre_id AS poblacion_madre_id,
	padre_hog AS poblacion_padre_hog,
	padre_id AS poblacion_padre_id,
	disc1 AS poblacion_disc1,
	disc2 AS poblacion_disc2,
	disc3 AS poblacion_disc3,
	disc4 AS poblacion_disc4,
	disc5 AS poblacion_disc5,
	disc6 AS poblacion_disc6,
	disc7 AS poblacion_disc7,
	causa1 AS poblacion_causa1,
	causa2 AS poblacion_causa2,
	causa3 AS poblacion_causa3,
	causa4 AS poblacion_causa4,
	causa5 AS poblacion_causa5,
	causa6 AS poblacion_causa6,
	causa7 AS poblacion_causa7,
	hablaind AS poblacion_hablaind,
	lenguaind AS poblacion_lenguaind,
	hablaesp AS poblacion_hablaesp,
	comprenind AS poblacion_comprenind,
	etnia AS poblacion_etnia,
	alfabetism AS poblacion_alfabetism,
	asis_esc AS poblacion_asis_esc,
	nivel AS poblacion_nivel,
	grado AS poblacion_grado,
	tipoesc AS poblacion_tipoesc,
	tiene_b AS poblacion_tiene_b,
	otorg_b AS poblacion_otorg_b,
	forma_b AS poblacion_forma_b,
	tiene_c AS poblacion_tiene_c,
	otorg_c AS poblacion_otorg_c,
	forma_c AS poblacion_forma_c,
	nivelaprob AS poblacion_nivelaprob,
	gradoaprob AS poblacion_gradoaprob,
	antec_esc AS poblacion_antec_esc,
	residencia AS poblacion_residencia,
	edo_conyug AS poblacion_edo_conyug,
	pareja_hog AS poblacion_pareja_hog,
	conyuge_id AS poblacion_conyuge_id,
	segsoc AS poblacion_segsoc,
	ss_aa AS poblacion_ss_aa,
	ss_mm AS poblacion_ss_mm,
	redsoc_1 AS poblacion_redsoc_1,
	redsoc_2 AS poblacion_redsoc_2,
	redsoc_3 AS poblacion_redsoc_3,
	redsoc_4 AS poblacion_redsoc_4,
	redsoc_5 AS poblacion_redsoc_5,
	redsoc_6 AS poblacion_redsoc_6,
	hor_1 AS poblacion_hor_1,
	min_1 AS poblacion_min_1,
	usotiempo1 AS poblacion_usotiempo1,
	hor_2 AS poblacion_hor_2,
	min_2 AS poblacion_min_2,
	usotiempo2 AS poblacion_usotiempo2,
	hor_3 AS poblacion_hor_3,
	min_3 AS poblacion_min_3,
	usotiempo3 AS poblacion_usotiempo3,
	hor_4 AS poblacion_hor_4,
	min_4 AS poblacion_min_4,
	usotiempo4 AS poblacion_usotiempo4,
	hor_5 AS poblacion_hor_5,
	min_5 AS poblacion_min_5,
	usotiempo5 AS poblacion_usotiempo5,
	hor_6 AS poblacion_hor_6,
	min_6 AS poblacion_min_6,
	usotiempo6 AS poblacion_usotiempo6,
	hor_7 AS poblacion_hor_7,
	min_7 AS poblacion_min_7,
	usotiempo7 AS poblacion_usotiempo7,
	hor_8 AS poblacion_hor_8,
	min_8 AS poblacion_min_8,
	usotiempo8 AS poblacion_usotiempo8,
	segpop AS poblacion_segpop,
	atemed AS poblacion_atemed,
	inst_1 AS poblacion_inst_1,
	inst_2 AS poblacion_inst_2,
	inst_3 AS poblacion_inst_3,
	inst_4 AS poblacion_inst_4,
	inst_5 AS poblacion_inst_5,
	inscr_1 AS poblacion_inscr_1,
	inscr_2 AS poblacion_inscr_2,
	inscr_3 AS poblacion_inscr_3,
	inscr_4 AS poblacion_inscr_4,
	inscr_5 AS poblacion_inscr_5,
	inscr_6 AS poblacion_inscr_6,
	inscr_7 AS poblacion_inscr_7,
	inscr_8 AS poblacion_inscr_8,
	prob_anio AS poblacion_prob_anio,
	prob_mes AS poblacion_prob_mes,
	prob_sal AS poblacion_prob_sal,
	aten_sal AS poblacion_aten_sal,
	servmed_1 AS poblacion_servmed_1,
	servmed_2 AS poblacion_servmed_2,
	servmed_3 AS poblacion_servmed_3,
	servmed_4 AS poblacion_servmed_4,
	servmed_5 AS poblacion_servmed_5,
	servmed_6 AS poblacion_servmed_6,
	servmed_7 AS poblacion_servmed_7,
	servmed_8 AS poblacion_servmed_8,
	servmed_9 AS poblacion_servmed_9,
	servmed_10 AS poblacion_servmed_10,
	servmed_11 AS poblacion_servmed_11,
	hh_lug AS poblacion_hh_lug,
	mm_lug AS poblacion_mm_lug,
	hh_esp AS poblacion_hh_esp,
	mm_esp AS poblacion_mm_esp,
	pagoaten_1 AS poblacion_pagoaten_1,
	pagoaten_2 AS poblacion_pagoaten_2,
	pagoaten_3 AS poblacion_pagoaten_3,
	pagoaten_4 AS poblacion_pagoaten_4,
	pagoaten_5 AS poblacion_pagoaten_5,
	pagoaten_6 AS poblacion_pagoaten_6,
	pagoaten_7 AS poblacion_pagoaten_7,
	noatenc_1 AS poblacion_noatenc_1,
	noatenc_2 AS poblacion_noatenc_2,
	noatenc_3 AS poblacion_noatenc_3,
	noatenc_4 AS poblacion_noatenc_4,
	noatenc_5 AS poblacion_noatenc_5,
	noatenc_6 AS poblacion_noatenc_6,
	noatenc_7 AS poblacion_noatenc_7,
	noatenc_8 AS poblacion_noatenc_8,
	noatenc_9 AS poblacion_noatenc_9,
	noatenc_10 AS poblacion_noatenc_10,
	noatenc_11 AS poblacion_noatenc_11,
	noatenc_12 AS poblacion_noatenc_12,
	noatenc_13 AS poblacion_noatenc_13,
	noatenc_14 AS poblacion_noatenc_14,
	noatenc_15 AS poblacion_noatenc_15,
	noatenc_16 AS poblacion_noatenc_16,
	norecib_1 AS poblacion_norecib_1,
	norecib_2 AS poblacion_norecib_2,
	norecib_3 AS poblacion_norecib_3,
	norecib_4 AS poblacion_norecib_4,
	norecib_5 AS poblacion_norecib_5,
	norecib_6 AS poblacion_norecib_6,
	norecib_7 AS poblacion_norecib_7,
	norecib_8 AS poblacion_norecib_8,
	norecib_9 AS poblacion_norecib_9,
	norecib_10 AS poblacion_norecib_10,
	norecib_11 AS poblacion_norecib_11,
	razon_1 AS poblacion_razon_1,
	razon_2 AS poblacion_razon_2,
	razon_3 AS poblacion_razon_3,
	razon_4 AS poblacion_razon_4,
	razon_5 AS poblacion_razon_5,
	razon_6 AS poblacion_razon_6,
	razon_7 AS poblacion_razon_7,
	razon_8 AS poblacion_razon_8,
	razon_9 AS poblacion_razon_9,
	razon_10 AS poblacion_razon_10,
	razon_11 AS poblacion_razon_11,
	diabetes AS poblacion_diabetes,
	pres_alta AS poblacion_pres_alta,
	peso AS poblacion_peso,
	segvol_1 AS poblacion_segvol_1,
	segvol_2 AS poblacion_segvol_2,
	segvol_3 AS poblacion_segvol_3,
	segvol_4 AS poblacion_segvol_4,
	segvol_5 AS poblacion_segvol_5,
	segvol_6 AS poblacion_segvol_6,
	segvol_7 AS poblacion_segvol_7,
	hijos_viv AS poblacion_hijos_viv,
	hijos_mue AS poblacion_hijos_mue,
	hijos_sob AS poblacion_hijos_sob,
	trabajo_mp AS poblacion_trabajo_mp,
	motivo_aus AS poblacion_motivo_aus,
	act_pnea1 AS poblacion_act_pnea1,
	act_pnea2 AS poblacion_act_pnea2,
	num_trabaj AS poblacion_num_trabaj
	FROM clean.enigh_poblacion) pob
USING (folioviv, foliohog, numren)

/* Join with person x job level work information */
FULL JOIN
(SELECT folioviv,
	foliohog,
	numren,
	id_trabajo AS trabajos_id_trabajo,
	trapais AS trabajos_trapais,
	subor AS trabajos_subor,
	indep AS trabajos_indep,
	personal AS trabajos_personal,
	pago AS trabajos_pago,
	contrato AS trabajos_contrato,
	tipocontr AS trabajos_tipocontr,
	pres_1 AS trabajos_pres_1,
	pres_2 AS trabajos_pres_2,
	pres_3 AS trabajos_pres_3,
	pres_4 AS trabajos_pres_4,
	pres_5 AS trabajos_pres_5,
	pres_6 AS trabajos_pres_6,
	pres_7 AS trabajos_pres_7,
	pres_8 AS trabajos_pres_8,
	pres_9 AS trabajos_pres_9,
	pres_10 AS trabajos_pres_10,
	pres_11 AS trabajos_pres_11,
	pres_12 AS trabajos_pres_12,
	pres_13 AS trabajos_pres_13,
	pres_14 AS trabajos_pres_14,
	pres_15 AS trabajos_pres_15,
	pres_16 AS trabajos_pres_16,
	pres_17 AS trabajos_pres_17,
	pres_18 AS trabajos_pres_18,
	pres_19 AS trabajos_pres_19,
	pres_20 AS trabajos_pres_20,
	htrab AS trabajos_htrab,
	sinco AS trabajos_sinco,
	scian AS trabajos_scian,
	clas_emp AS trabajos_clas_emp,
	tam_emp AS trabajos_tam_emp,
	no_ing AS trabajos_no_ing,
	tiene_suel AS trabajos_tiene_suel,
	tipoact AS trabajos_tipoact,
	socios AS trabajos_socios,
	soc_nr1 AS trabajos_soc_nr1,
	soc_nr2 AS trabajos_soc_nr2,
	soc_resp AS trabajos_soc_resp,
	otra_act AS trabajos_otra_act,
	tipoact2 AS trabajos_tipoact2,
	tipoact3 AS trabajos_tipoact3,
	tipoact4 AS trabajos_tipoact4,
	lugar AS trabajos_lugar,
	conf_pers AS trabajos_conf_pers,
	reg_not AS trabajos_reg_not,
	reg_cont AS trabajos_reg_cont,
	com_fis AS trabajos_com_fis
	FROM clean.enigh_trabajos) trabajos
USING (folioviv, foliohog, numren)

/* Join with household level viviendas information */
FULL JOIN
(SELECT folioviv,
	locality_id,
	tipo_viv AS vivi_tipo_viv,
	ageb AS vivi_ageb,
	tam_loc AS vivi_tam_loc,
	mat_pared AS vivi_mat_pared,
	mat_techos AS vivi_mat_techos,
	mat_pisos AS vivi_mat_pisos,
	antiguedad AS vivi_antiguedad,
	antigua_ne AS vivi_antigua_ne,
	cocina AS vivi_cocina,
	cocina_dor AS vivi_cocina_dor,
	cuart_dorm AS vivi_cuart_dorm,
	num_cuarto AS vivi_num_cuarto,
	disp_agua AS vivi_disp_agua,
	dotac_agua AS vivi_dotac_agua,
	excusado AS vivi_excusado,
	uso_compar AS vivi_uso_compar,
	sanit_agua AS vivi_sanit_agua,
	biodigest AS vivi_biodigest,
	bano_comp AS vivi_bano_comp,
	bano_excus AS vivi_bano_excus,
	bano_regad AS vivi_bano_regad,
	drenaje AS vivi_drenaje,
	disp_elect AS vivi_disp_elect,
	focos_inca AS vivi_focos_inca,
	focos_ahor AS vivi_focos_ahor,
	combustible AS vivi_combustible,
	estufa_chi AS vivi_estufa_chi,
	eli_basura AS vivi_eli_basura,
	tenencia AS vivi_tenencia,
	renta AS vivi_renta,
	estim_pago AS vivi_estim_pago,
	pago_viv AS vivi_pago_viv,
	pago_mesp AS vivi_pago_mesp,
	tipo_adqui AS vivi_tipo_adqui,
	viv_usada AS vivi_viv_usada,
	tipo_finan AS vivi_tipo_finan,
	num_dueno1 AS vivi_num_dueno1,
	hog_dueno1 AS vivi_hog_dueno1,
	num_dueno2 AS vivi_num_dueno2,
	hog_dueno2 AS vivi_hog_dueno2,
	escrituras AS vivi_escrituras,
	lavadero AS vivi_lavadero,
	fregadero AS vivi_fregadero,
	regadera AS vivi_regadera,
	tinaco_azo AS vivi_tinaco_azo,
	cisterna AS vivi_cisterna,
	pileta AS vivi_pileta,
	calent_sol AS vivi_calent_sol,
	calent_gas AS vivi_calent_gas,
	medidor_luz AS vivi_medidor_luz,
	bomba_agua AS vivi_bomba_agua,
	tanque_gas AS vivi_tanque_gas,
	aire_acond AS vivi_aire_acond,
	calefacc AS vivi_calefacc,
	tot_resid AS vivi_tot_resid,
	tot_hom AS vivi_tot_hom,
	tot_muj AS vivi_tot_muj,
	tot_hog AS vivi_tot_hog,
	est_socio AS vivi_est_socio,
	est_dis AS vivi_est_dis,
	upm AS vivi_upm,
	factor_viv AS vivi_factor_viv
FROM clean.enigh_vivi) vivi
USING (folioviv)

FULL JOIN
(SELECT folioviv,
        foliohog,
	huespedes AS hogares_huespedes,
	huesp_come AS hogares_huesp_come,
	num_trab_d AS hogares_num_trab_d,
	trab_come AS hogares_trab_come,
	acc_alim1 AS hogares_acc_alim1,
	acc_alim2 AS hogares_acc_alim2,
	acc_alim3 AS hogares_acc_alim3,
	acc_alim4 AS hogares_acc_alim4,
	acc_alim5 AS hogares_acc_alim5,
	acc_alim6 AS hogares_acc_alim6,
	acc_alim7 AS hogares_acc_alim7,
	acc_alim8 AS hogares_acc_alim8,
	acc_alim9 AS hogares_acc_alim9,
	acc_alim10 AS hogares_acc_alim10,
	acc_alim11 AS hogares_acc_alim11,
	acc_alim12 AS hogares_acc_alim12,
	acc_alim13 AS hogares_acc_alim13,
	acc_alim14 AS hogares_acc_alim14,
	acc_alim15 AS hogares_acc_alim15,
	acc_alim16 AS hogares_acc_alim16,
	alim17_1 AS hogares_alim17_1,
	alim17_2 AS hogares_alim17_2,
	alim17_3 AS hogares_alim17_3,
	alim17_4 AS hogares_alim17_4,
	alim17_5 AS hogares_alim17_5,
	alim17_6 AS hogares_alim17_6,
	alim17_7 AS hogares_alim17_7,
	alim17_8 AS hogares_alim17_8,
	alim17_9 AS hogares_alim17_9,
	alim17_10 AS hogares_alim17_10,
	alim17_11 AS hogares_alim17_11,
	alim17_12 AS hogares_alim17_12,
	acc_alim18 AS hogares_acc_alim18,
	telefono AS hogares_telefono,
	celular AS hogares_celular,
	tv_paga AS hogares_tv_paga,
	conex_inte AS hogares_conex_inte,
	num_auto AS hogares_num_auto,
	anio_auto AS hogares_anio_auto,
	num_van AS hogares_num_van,
	anio_van AS hogares_anio_van,
	num_pickup AS hogares_num_pickup,
	anio_pickup AS hogares_anio_pickup,
	num_moto AS hogares_num_moto,
	anio_moto AS hogares_anio_moto,
	num_bici AS hogares_num_bici,
	anio_bici AS hogares_anio_bici,
	num_trici AS hogares_num_trici,
	anio_trici AS hogares_anio_trici,
	num_carret AS hogares_num_carret,
	anio_carret AS hogares_anio_carret,
	num_canoa AS hogares_num_canoa,
	anio_canoa AS hogares_anio_canoa,
	num_otro AS hogares_num_otro,
	anio_otro AS hogares_anio_otro,
	num_ester AS hogares_num_ester,
	anio_ester AS hogares_anio_ester,
	num_grab AS hogares_num_grab,
	anio_grab AS hogares_anio_grab,
	num_radio AS hogares_num_radio,
	anio_radio AS hogares_anio_radio,
	num_tva AS hogares_num_tva,
	anio_tva AS hogares_anio_tva,
	num_tvd AS hogares_num_tvd,
	anio_tvd AS hogares_anio_tvd,
	num_dvd AS hogares_num_dvd,
	anio_dvd AS hogares_anio_dvd,
	num_video AS hogares_num_video,
	anio_video AS hogares_anio_video,
	num_licua AS hogares_num_licua,
	anio_licua AS hogares_anio_licua,
	num_tosta AS hogares_num_tosta,
	anio_tosta AS hogares_anio_tosta,
	num_micro AS hogares_num_micro,
	anio_micro AS hogares_anio_micro,
	num_refri AS hogares_num_refri,
	anio_refri AS hogares_anio_refri,
	num_estuf AS hogares_num_estuf,
	anio_estuf AS hogares_anio_estuf,
	num_lavad AS hogares_num_lavad,
	anio_lavad AS hogares_anio_lavad,
	num_planc AS hogares_num_planc,
	anio_planc AS hogares_anio_planc,
	num_maqui AS hogares_num_maqui,
	anio_maqui AS hogares_anio_maqui,
	num_venti AS hogares_num_venti,
	anio_venti AS hogares_anio_venti,
	num_aspir AS hogares_num_aspir,
	anio_aspir AS hogares_anio_aspir,
	num_compu AS hogares_num_compu,
	anio_compu AS hogares_anio_compu,
	num_impre AS hogares_num_impre,
	anio_impre AS hogares_anio_impre,
	num_juego AS hogares_num_juego,
	anio_juego AS hogares_anio_juego,
	tsalud1_h AS hogares_tsalud1_h,
	tsalud1_m AS hogares_tsalud1_m,
	habito_1 AS hogares_habito_1,
	habito_2 AS hogares_habito_2,
	habito_3 AS hogares_habito_3,
	habito_4 AS hogares_habito_4,
	habito_5 AS hogares_habito_5,
	habito_6 AS hogares_habito_6,
	consumo AS hogares_consumo,
	nr_viv AS hogares_nr_viv,
	tarjeta AS hogares_tarjeta,
	pagotarjet AS hogares_pagotarjet,
	regalotar AS hogares_regalotar,
	regalodado AS hogares_regalodado,
	autocons AS hogares_autocons,
	regalos AS hogares_regalos,
	remunera AS hogares_remunera,
	transferen AS hogares_transferen,
	parto_g AS hogares_parto_g,
	embarazo_g AS hogares_embarazo_g,
	negcua AS hogares_negcua,
	est_alim AS hogares_est_alim,
	est_trans AS hogares_est_trans,
	factor_hog AS hogares_factor_hog
FROM clean.enigh_hogares) hogares
USING (folioviv, foliohog)


FULL JOIN
(SELECT folioviv,
        foliohog,
        tam_loc AS concentradohogar_tam_loc,
	clase_hog AS concentradohogar_clase_hog,
	sexo_jefe AS concentradohogar_sexo_jefe,
	edad_jefe AS concentradohogar_edad_jefe,
	educa_jefe AS concentradohogar_educa_jefe,
	tot_integ AS concentradohogar_tot_integ,
	hombres AS concentradohogar_hombres,
	mujeres AS concentradohogar_mujeres,
	mayores AS concentradohogar_mayores,
	menores AS concentradohogar_menores,
	p12_64 AS concentradohogar_p12_64,
	p65mas AS concentradohogar_p65mas,
	ocupados AS concentradohogar_ocupados,
	percep_ing AS concentradohogar_percep_ing,
	perc_ocupa AS concentradohogar_perc_ocupa,
	ing_cor AS concentradohogar_ing_cor,
	ingtrab AS concentradohogar_ingtrab,
	trabajo AS concentradohogar_trabajo,
	sueldos AS concentradohogar_sueldos,
	horas_extr AS concentradohogar_horas_extr,
	comisiones AS concentradohogar_comisiones,
	aguinaldo AS concentradohogar_aguinaldo,
	indemtrab AS concentradohogar_indemtrab,
	otra_rem AS concentradohogar_otra_rem,
	remu_espec AS concentradohogar_remu_espec,
	negocio AS concentradohogar_negocio,
	noagrop AS concentradohogar_noagrop,
	industria AS concentradohogar_industria,
	comercio AS concentradohogar_comercio,
	servicios AS concentradohogar_servicios,
	agrope AS concentradohogar_agrope,
	agricolas AS concentradohogar_agricolas,
	pecuarios AS concentradohogar_pecuarios,
	reproducc AS concentradohogar_reproducc,
	pesca AS concentradohogar_pesca,
	otros_trab AS concentradohogar_otros_trab,
	rentas AS concentradohogar_rentas,
	utilidad AS concentradohogar_utilidad,
	arrenda AS concentradohogar_arrenda,
	transfer AS concentradohogar_transfer,
	jubilacion AS concentradohogar_jubilacion,
	becas AS concentradohogar_becas,
	donativos AS concentradohogar_donativos,
	remesas AS concentradohogar_remesas,
	bene_gob AS concentradohogar_bene_gob,
	transf_hog AS concentradohogar_transf_hog,
	trans_inst AS concentradohogar_trans_inst,
	estim_alqu AS concentradohogar_estim_alqu,
	otros_ing AS concentradohogar_otros_ing,
	gasto_mon AS concentradohogar_gasto_mon,
	alimentos AS concentradohogar_alimentos,
	ali_dentro AS concentradohogar_ali_dentro,
	cereales AS concentradohogar_cereales,
	carnes AS concentradohogar_carnes,
	pescado AS concentradohogar_pescado,
	leche AS concentradohogar_leche,
	huevo AS concentradohogar_huevo,
	aceites AS concentradohogar_aceites,
	tuberculo AS concentradohogar_tuberculo,
	verduras AS concentradohogar_verduras,
	frutas AS concentradohogar_frutas,
	azucar AS concentradohogar_azucar,
	cafe AS concentradohogar_cafe,
	especias AS concentradohogar_especias,
	otros_alim AS concentradohogar_otros_alim,
	bebidas AS concentradohogar_bebidas,
	ali_fuera AS concentradohogar_ali_fuera,
	tabaco AS concentradohogar_tabaco,
	vesti_calz AS concentradohogar_vesti_calz,
	vestido AS concentradohogar_vestido,
	calzado AS concentradohogar_calzado,
	vivienda AS concentradohogar_vivienda,
	alquiler AS concentradohogar_alquiler,
	pred_cons AS concentradohogar_pred_cons,
	agua AS concentradohogar_agua,
	energia AS concentradohogar_energia,
	limpieza AS concentradohogar_limpieza,
	cuidados AS concentradohogar_cuidados,
	utensilios AS concentradohogar_utensilios,
	enseres AS concentradohogar_enseres,
	salud AS concentradohogar_salud,
	atenc_ambu AS concentradohogar_atenc_ambu,
	hospital AS concentradohogar_hospital,
	medicinas AS concentradohogar_medicinas,
	transporte AS concentradohogar_transporte,
	publico AS concentradohogar_publico,
	foraneo AS concentradohogar_foraneo,
	adqui_vehi AS concentradohogar_adqui_vehi,
	mantenim AS concentradohogar_mantenim,
	refaccion AS concentradohogar_refaccion,
	combus AS concentradohogar_combus,
	comunica AS concentradohogar_comunica,
	educa_espa AS concentradohogar_educa_espa,
	educacion AS concentradohogar_educacion,
	esparci AS concentradohogar_esparci,
	paq_turist AS concentradohogar_paq_turist,
	personales AS concentradohogar_personales,
	cuida_pers AS concentradohogar_cuida_pers,
	acces_pers AS concentradohogar_acces_pers,
	otros_gas AS concentradohogar_otros_gas,
	transf_gas AS concentradohogar_transf_gas,
	percep_tot AS concentradohogar_percep_tot,
	retiro_inv AS concentradohogar_retiro_inv,
	prestamos AS concentradohogar_prestamos,
	otras_perc AS concentradohogar_otras_perc,
	ero_nm_viv AS concentradohogar_ero_nm_viv,
	ero_nm_hog AS concentradohogar_ero_nm_hog,
	erogac_tot AS concentradohogar_erogac_tot,
	cuota_viv AS concentradohogar_cuota_viv,
	mater_serv AS concentradohogar_mater_serv,
	material AS concentradohogar_material,
	servicio AS concentradohogar_servicio,
	deposito AS concentradohogar_deposito,
	prest_terc AS concentradohogar_prest_terc,
	pago_tarje AS concentradohogar_pago_tarje,
	deudas AS concentradohogar_deudas,
	balance AS concentradohogar_balance,
	otras_erog AS concentradohogar_otras_erog,
	smg AS concentradohogar_smg
FROM clean.enigh_concentrado) concentradohogar
USING (folioviv, foliohog)

/* join in locality information */
LEFT JOIN
(SELECT locality_id, locality_name as localidades_locality_name, municipality_name as localidades_municipality_name, substring(locality_id from 1 for 5) as municipality_id, state_name as localidades_state_name, urban as localidades_urban, population as localidades_population, population_female as localidades_population_female, population_age_0_to_2 as localidades_population_age_0_to_2, population_age_0_to_2_female as localidades_population_age_0_to_2_female, population_age_greater_3 as localidades_population_age_greater_3, population_age_greater_3_female as localidades_population_age_greater_3_female, population_age_greater_5 as localidades_population_age_greater_5, population_age_greater_5_female as localidades_population_age_greater_5_female, population_age_greater_12 as localidades_population_age_greater_12, population_age_greater_12_female as localidades_population_age_greater_12_female, population_age_greater_15 as localidades_population_age_greater_15, population_age_greater_15_female as localidades_population_age_greater_15_female, population_age_greater_18 as localidades_population_age_greater_18, population_age_greater_18_female as localidades_population_age_greater_18_female, population_age_greater_60 as localidades_population_age_greater_60, population_age_greater_60_female as localidades_population_age_greater_60_female, fertility_rate as localidades_fertility_rate, population_born_in_state as localidades_population_born_in_state, population_men_born_in_state as localidades_population_men_born_in_state, population_born_out_of_state as localidades_population_born_out_of_state, population_men_born_out_of_state as localidades_population_men_born_out_of_state, population_immigrant_since_2005 as localidades_population_immigrant_since_2005, population_immigrant_men_since_2005 as localidades_population_immigrant_men_since_2005, population_speak_indigenous as localidades_population_speak_indigenous, population_male_speak_indigenous as localidades_population_male_speak_indigenous, population_not_speak_spanish as localidades_population_not_speak_spanish, population_male_not_speak_spanish as localidades_population_male_not_speak_spanish, population_speak_indigenous_and_spanish as localidades_population_speak_indigenous_and_spanish, population_male_speak_indigenous_and_spanish as localidades_population_male_speak_indigenous_and_spanish, n_indigenous_households as localidades_n_indigenous_households, population_limited_activity as localidades_population_limited_activity, population_limited_mobility as localidades_population_limited_mobility, population_limited_vision as localidades_population_limited_vision, population_limited_speaking as localidades_population_limited_speaking, population_limited_hearing as localidades_population_limited_hearing, population_limited_senility as localidades_population_limited_senility, population_limited_mental as localidades_population_limited_mental, population_ages_3_5_no_school as localidades_population_ages_3_5_no_school, population_male_ages_3_5_no_school as localidades_population_male_ages_3_5_no_school, population_ages_6_11_no_school as localidades_population_ages_6_11_no_school, population_male_ages_6_11_no_school as localidades_population_male_ages_6_11_no_school, population_ages_12_14_no_school as localidades_population_ages_12_14_no_school, population_male_ages_12_14_no_school as localidades_population_male_ages_12_14_no_school, population_ages_15_17_in_school as localidades_population_ages_15_17_in_school, population_male_ages_15_17_in_school as localidades_population_male_ages_15_17_in_school, population_ages_18_24_in_school as localidades_population_ages_18_24_in_school, population_male_ages_18_24_in_school as localidades_population_male_ages_18_24_in_school, population_ages_8_14_illiterate as localidades_population_ages_8_14_illiterate, population_male_ages_8_14_illiterate as localidades_population_male_ages_8_14_illiterate, population_age_over_15_illiterate as localidades_population_age_over_15_illiterate, population_male_age_over_15_illiterate as localidades_population_male_age_over_15_illiterate, population_age_over_15_no_school as localidades_population_age_over_15_no_school, population_male_age_over_15_no_school as localidades_population_male_age_over_15_no_school, population_age_over_15_no_primary_school as localidades_population_age_over_15_no_primary_school, population_male_age_over_15_no_primary_school as localidades_population_male_age_over_15_no_primary_school, population_age_over_15_no_secondary_school as localidades_population_age_over_15_no_secondary_school, population_male_age_over_15_no_secondary_school as localidades_population_male_age_over_15_no_secondary_school, population_age_over_18_basic_schooling as localidades_population_age_over_18_basic_schooling, population_male_age_over_18_basic_schooling as localidades_population_male_age_over_18_basic_schooling, population_economically_active as localidades_population_economically_active, population_male_economically_active as localidades_population_male_economically_active, population_not_economically_active as localidades_population_not_economically_active, population_male_not_economically_active as localidades_population_male_not_economically_active, population_employed as localidades_population_employed, population_male_employed as localidades_population_male_employed, population_unemployed as localidades_population_unemployed, population_male_unemployed as localidades_population_male_unemployed, population_no_health_services as localidades_population_no_health_services, population_entitled_to_health_services as localidades_population_entitled_to_health_services, population_covered_by_imss as localidades_population_covered_by_imss, population_covered_by_issste as localidades_population_covered_by_issste, population_covered_by_state_issste as localidades_population_covered_by_state_issste, population_covered_by_seguro_popular as localidades_population_covered_by_seguro_popular, population_over_12_unmarried as localidades_population_over_12_unmarried, population_over_12_married as localidades_population_over_12_married, population_over_12_divorced as localidades_population_over_12_divorced, population_catholic as localidades_population_catholic, population_other_christian as localidades_population_other_christian, population_other_religions as localidades_population_other_religions, population_non_religious as localidades_population_non_religious, n_census_households as localidades_n_census_households, n_male_head_of_household as localidades_n_male_head_of_household, n_female_head_of_household as localidades_n_female_head_of_household, n_census_persons as localidades_n_census_persons, n_people_private_homes as localidades_n_people_private_homes, average_number_home_occupants as localidades_average_number_home_occupants, average_number_occupants_per_room as localidades_average_number_occupants_per_room, n_different_floor_material as localidades_n_different_floor_material, n_private_homes_dirt_floors as localidades_n_private_homes_dirt_floors, n_homes_with_one_bedroom as localidades_n_homes_with_one_bedroom, n_homes_with_at_least_two_bedrooms as localidades_n_homes_with_at_least_two_bedrooms, n_homes_with_one_room as localidades_n_homes_with_one_room, n_homes_with_two_rooms as localidades_n_homes_with_two_rooms, n_homes_with_three_or_more_rooms as localidades_n_homes_with_three_or_more_rooms, n_homes_with_electricity as localidades_n_homes_with_electricity, n_homes_without_electricity as localidades_n_homes_without_electricity, n_homes_with_plumbing as localidades_n_homes_with_plumbing, n_homes_without_plumbing as localidades_n_homes_without_plumbing, n_homes_with_toilet as localidades_n_homes_with_toilet, n_homes_with_sewage_access as localidades_n_homes_with_sewage_access, n_homes_with_full_infrastructure as localidades_n_homes_with_full_infrastructure, n_homes_without_any_goods as localidades_n_homes_without_any_goods, n_homes_with_radio as localidades_n_homes_with_radio, n_homes_with_tv as localidades_n_homes_with_tv, n_homes_with_refigerador as localidades_n_homes_with_refigerador, n_homes_with_washing_machine as localidades_n_homes_with_washing_machine, n_homes_with_car as localidades_n_homes_with_car, n_homes_with_computer as localidades_n_homes_with_computer, n_homes_with_telephone as localidades_n_homes_with_telephone, n_homes_with_cell_hone as localidades_n_homes_with_cell_hone, n_homes_with_internet as localidades_n_homes_with_internet, n_households_in_poverty as localidades_n_households_in_poverty, n_people_in_poverty as localidades_n_people_in_poverty, n_housholds_without_basic_housing_services as localidades_n_housholds_without_basic_housing_services, n_people_without_basic_housing_services as localidades_n_people_without_basic_housing_services, n_households_without_water as localidades_n_households_without_water, n_people_without_water as localidades_n_people_without_water, n_households_without_sewage as localidades_n_households_without_sewage, n_people_without_sewage as localidades_n_people_without_sewage, n_households_without_electricity as localidades_n_households_without_electricity, n_people_without_electricity as localidades_n_people_without_electricity, n_households_without_quality_living_space as localidades_n_households_without_quality_living_space, n_people_without_quality_living_space as localidades_n_people_without_quality_living_space, n_households_dirt_floor as localidades_n_households_dirt_floor, n_people_dirt_floor as localidades_n_people_dirt_floor, n_households_overcrowding as localidades_n_households_overcrowding, n_people_overcrowding as localidades_n_people_overcrowding, n_households_no_health as localidades_n_households_no_health, n_people_no_health as localidades_n_people_no_health, n_households_lack_education as localidades_n_households_lack_education, n_people_lack_education as localidades_n_people_lack_education, latitude as localidades_latitude, longitude as localidades_longitude
	FROM clean.localidades) localidadees
USING (locality_id)

/* join with irs data, since it's a feature on their original linear regression*/
LEFT JOIN 
clean.indice_de_rezago_social
USING (municipality_id)

ORDER BY folioviv, numren, transaction_type;
