create table clean.enigh_agropecuario as
select 
folioviv,
foliohog,
numren,
id_trabajo,
tipoact,
cose_cria,
prep_deriv,
case when t_emp = ' ' then NULL else cast(t_emp as numeric) end,
case when h_emp = ' ' then NULL else cast(h_emp as numeric) end,
case when m_emp = ' ' then NULL else cast(m_emp as numeric) end,
case when t_cpago = ' ' then NULL else cast(t_cpago as numeric) end,
case when h_cpago = ' ' then NULL else cast(h_cpago as numeric) end,
case when m_cpago = ' ' then NULL else cast(m_cpago as numeric) end,
case when t_ispago = ' ' then NULL else cast(t_ispago as numeric) end,
case when h_ispago = ' ' then NULL else cast(h_ispago as numeric) end,
case when m_ispago = ' ' then NULL else cast(m_ispago as numeric) end,
case when t_nispago = ' ' then NULL else cast(t_nispago as numeric) end,
case when h_nispago = ' ' then NULL else cast(h_nispago as numeric) end,
case when m_nispago = ' ' then NULL else cast(m_nispago as numeric) end,
case when valrema = ' ' then NULL else cast(valrema as numeric) end,
case when valproc = ' ' then NULL else cast(valproc as numeric) end,
apoyo,
case when apoyo_1 = ' ' then NULL else cast(apoyo_1 as numeric) end,
case when apoyo_2 = ' ' then NULL else cast(apoyo_2 as numeric) end,
case when apoyo_3 = ' ' then NULL else cast(apoyo_3 as numeric) end,
case when apoyo_4 = ' ' then NULL else cast(apoyo_4 as numeric) end,
case when apoyo_5 = ' ' then NULL else cast(apoyo_5 as numeric) end,
case when apoyo_6 = ' ' then NULL else cast(apoyo_6 as numeric) end,
case when apoyo_7 = ' ' then NULL else cast(apoyo_7 as numeric) end,
case when apoyo_8 = ' ' then NULL else cast(apoyo_8 as numeric) end,
case when procampo = ' ' then NULL else cast(procampo as numeric) end,
mesproc,
progan,
case when mesprogan = ' ' then NULL else cast(mesprogan as numeric) end,
case when reg_not = ' ' then NULL else cast(reg_not as numeric) end,
case when reg_cont = ' ' then NULL else cast(reg_cont as numeric) end,
case when com_fis = ' ' then NULL else cast(com_fis as numeric) end,
ventas,
autocons,
otrosnom,
gasneg,
ventas_tri,
auto_tri,
otros_tri,
gasto_tri,
ing_tri,
ero_tri
FROM 
raw.inegi_agropecuario_2014;
