create table clean.enigh_concentrado as
select 
folioviv,
foliohog,
ubica_geo,
ageb,
tam_loc,
est_socio,
est_dis,
upm,
case when factor_hog = ' ' then NULL else cast(factor_hog as numeric) end,
clase_hog,
sexo_jefe,
case when edad_jefe = ' ' then NULL else cast(edad_jefe as numeric) end,
educa_jefe,
case when tot_integ = ' ' then NULL else cast(tot_integ as numeric) end,
case when hombres = ' ' then NULL else cast(hombres as numeric) end,
case when mujeres = ' ' then NULL else cast(mujeres as numeric) end,
case when mayores = ' ' then NULL else cast(mayores as numeric) end,
case when menores = ' ' then NULL else cast(menores as numeric) end,
case when p12_64 = ' ' then NULL else cast(p12_64 as numeric) end,
case when p65mas = ' ' then NULL else cast(p65mas as numeric) end,
case when ocupados = ' ' then NULL else cast(ocupados as numeric) end,
case when percep_ing = ' ' then NULL else cast(percep_ing as numeric) end,
case when perc_ocupa = ' ' then NULL else cast(perc_ocupa as numeric) end,
cast(replace(ing_cor,',','.') as numeric) as ing_cor,
cast(replace(ingtrab,',','.') as numeric) as ingtrab,
cast(replace(trabajo,',','.') as numeric) as trabajo,
cast(replace(sueldos,',','.') as numeric) as sueldos,
cast(replace(horas_extr,',','.') as numeric) as horas_extr,
cast(replace(comisiones,',','.') as numeric) as comisiones,
cast(replace(aguinaldo,',','.') as numeric) as aguinaldo,
cast(replace(indemtrab,',','.') as numeric) as indemtrab,
cast(replace(otra_rem,',','.') as numeric) as otra_rem,
cast(replace(remu_espec,',','.') as numeric) as remu_espec,
cast(replace(negocio,',','.') as numeric) as negocio,
cast(replace(noagrop,',','.') as numeric) as noagrop,
cast(replace(industria,',','.') as numeric) as industria,
cast(replace(comercio,',','.') as numeric) as comercio,
cast(replace(servicios,',','.') as numeric) as servicios,
cast(replace(agrope,',','.') as numeric) as agrope,
cast(replace(agricolas,',','.') as numeric) as agricolas,
cast(replace(pecuarios,',','.') as numeric) as pecuarios,
cast(replace(reproducc,',','.') as numeric) as reproducc,
cast(replace(pesca,',','.') as numeric) as pesca,
cast(replace(otros_trab,',','.') as numeric) as otros_trab,
cast(replace(rentas,',','.') as numeric) as rentas,
cast(replace(utilidad,',','.') as numeric) as utilidad,
cast(replace(arrenda,',','.') as numeric) as arrenda,
cast(replace(transfer,',','.') as numeric) as transfer,
cast(replace(jubilacion,',','.') as numeric) as jubilacion,
cast(replace(becas,',','.') as numeric) as becas,
cast(replace(donativos,',','.') as numeric) as donativos,
cast(replace(remesas,',','.') as numeric) as remesas,
cast(replace(bene_gob,',','.') as numeric) as bene_gob,
cast(replace(transf_hog,',','.') as numeric) as transf_hog,
cast(replace(trans_inst,',','.') as numeric) as trans_inst,
cast(replace(estim_alqu,',','.') as numeric) as estim_alqu,
cast(replace(otros_ing,',','.') as numeric) as otros_ing,
cast(replace(gasto_mon,',','.') as numeric) as gasto_mon,
cast(replace(alimentos,',','.') as numeric) as alimentos,
cast(replace(ali_dentro,',','.') as numeric) as ali_dentro,
cast(replace(cereales,',','.') as numeric) as cereales,
cast(replace(carnes,',','.') as numeric) as carnes,
cast(replace(pescado,',','.') as numeric) as pescado,
cast(replace(leche,',','.') as numeric) as leche,
cast(replace(huevo,',','.') as numeric) as huevo,
cast(replace(aceites,',','.') as numeric) as aceites,
cast(replace(tuberculo,',','.') as numeric) as tuberculo,
cast(replace(verduras,',','.') as numeric) as verduras,
cast(replace(frutas,',','.') as numeric) as frutas,
cast(replace(azucar,',','.') as numeric) as azucar,
cast(replace(cafe,',','.') as numeric) as cafe,
cast(replace(especias,',','.') as numeric) as especias,
cast(replace(otros_alim,',','.') as numeric) as otros_alim,
cast(replace(bebidas,',','.') as numeric) as bebidas,
cast(replace(ali_fuera,',','.') as numeric) as ali_fuera,
cast(replace(tabaco,',','.') as numeric) as tabaco,
cast(replace(vesti_calz,',','.') as numeric) as vesti_calz,
cast(replace(vestido,',','.') as numeric) as vestido,
cast(replace(calzado,',','.') as numeric) as calzado,
cast(replace(vivienda,',','.') as numeric) as vivienda,
cast(replace(alquiler,',','.') as numeric) as alquiler,
cast(replace(pred_cons,',','.') as numeric) as pred_cons,
cast(replace(agua,',','.') as numeric) as agua,
cast(replace(energia,',','.') as numeric) as energia,
cast(replace(limpieza,',','.') as numeric) as limpieza,
cast(replace(cuidados,',','.') as numeric) as cuidados,
cast(replace(utensilios,',','.') as numeric) as utensilios,
cast(replace(enseres,',','.') as numeric) as enseres,
cast(replace(salud,',','.') as numeric) as salud,
cast(replace(atenc_ambu,',','.') as numeric) as atenc_ambu,
cast(replace(hospital,',','.') as numeric) as hospital,
cast(replace(medicinas,',','.') as numeric) as medicinas,
cast(replace(transporte,',','.') as numeric) as transporte,
cast(replace(publico,',','.') as numeric) as publico,
cast(replace(foraneo,',','.') as numeric) as foraneo,
cast(replace(adqui_vehi,',','.') as numeric) as adqui_vehi,
cast(replace(mantenim,',','.') as numeric) as mantenim,
cast(replace(refaccion,',','.') as numeric) as refaccion,
cast(replace(combus,',','.') as numeric) as combus,
cast(replace(comunica,',','.') as numeric) as comunica,
cast(replace(educa_espa,',','.') as numeric) as educa_espa,
cast(replace(educacion,',','.') as numeric) as educacion,
cast(replace(esparci,',','.') as numeric) as esparci,
cast(replace(paq_turist,',','.') as numeric) as paq_turist,
cast(replace(personales,',','.') as numeric) as personales,
cast(replace(cuida_pers,',','.') as numeric) as cuida_pers,
cast(replace(acces_pers,',','.') as numeric) as acces_pers,
cast(replace(otros_gas,',','.') as numeric) as otros_gas,
cast(replace(transf_gas,',','.') as numeric) as transf_gas,
cast(replace(percep_tot,',','.') as numeric) as percep_tot,
cast(replace(retiro_inv,',','.') as numeric) as retiro_inv,
cast(replace(prestamos,',','.') as numeric) as prestamos,
cast(replace(otras_perc,',','.') as numeric) as otras_perc,
cast(replace(ero_nm_viv,',','.') as numeric) as ero_nm_viv,
cast(replace(ero_nm_hog,',','.') as numeric) as ero_nm_hog,
cast(replace(erogac_tot,',','.') as numeric) as erogac_tot,
cast(replace(cuota_viv,',','.') as numeric) as cuota_viv,
cast(replace(mater_serv,',','.') as numeric) as mater_serv,
cast(replace(material,',','.') as numeric) as material,
cast(replace(servicio,',','.') as numeric) as servicio,
cast(replace(deposito,',','.') as numeric) as deposito,
cast(replace(prest_terc,',','.') as numeric) as prest_terc,
cast(replace(pago_tarje,',','.') as numeric) as pago_tarje,
cast(replace(deudas,',','.') as numeric) as deudas,
cast(replace(balance,',','.') as numeric) as balance,
cast(replace(otras_erog,',','.') as numeric) as otras_erog,
cast(replace(smg,',','.') as numeric) as smg
FROM
raw.inegi_concentrado_2014;
