create table clean.enigh_hogares as
select
folioviv,
foliohog,
case when huespedes = ' ' then NULL else cast( huespedes as numeric) end as huespedes,
case when huesp_come = ' ' then NULL else cast( huesp_come as numeric) end as huesp_come,
case when num_trab_d = ' ' then NULL else cast( num_trab_d as numeric) end as num_trab_d,
case when trab_come = ' ' then NULL else cast( trab_come as numeric) end as trab_come,
acc_alim1,
acc_alim2,
acc_alim3,
acc_alim4,
acc_alim5,
acc_alim6,
acc_alim7,
acc_alim8,
acc_alim9,
acc_alim10,
acc_alim11,
acc_alim12,
acc_alim13,
acc_alim14,
acc_alim15,
acc_alim16,
case when alim17_1 = ' ' then NULL else cast( alim17_1 as numeric) end as alim17_1,
case when alim17_2 = ' ' then NULL else cast( alim17_2 as numeric) end as alim17_2,
case when alim17_3 = ' ' then NULL else cast( alim17_3 as numeric) end as alim17_3,
case when alim17_4 = ' ' then NULL else cast( alim17_4 as numeric) end as alim17_4,
case when alim17_5 = ' ' then NULL else cast( alim17_5 as numeric) end as alim17_5,
case when alim17_6 = ' ' then NULL else cast( alim17_6 as numeric) end as alim17_6,
case when alim17_7 = ' ' then NULL else cast( alim17_7 as numeric) end as alim17_7,
case when alim17_8 = ' ' then NULL else cast( alim17_8 as numeric) end as alim17_8,
case when alim17_9 = ' ' then NULL else cast( alim17_9 as numeric) end as alim17_9,
case when alim17_10 = ' ' then NULL else cast( alim17_10 as numeric) end as alim17_10,
case when alim17_11 = ' ' then NULL else cast( alim17_11 as numeric) end as alim17_11,
case when alim17_12 = ' ' then NULL else cast( alim17_12 as numeric) end as alim17_12,
acc_alim18,
telefono,
celular,
tv_paga,
conex_inte,
case when num_auto = ' ' then NULL else cast(num_auto as numeric) end as num_auto,
anio_auto,
case when num_van = ' ' then NULL else cast(num_van as numeric) end as num_van, 
anio_van,
case when num_pickup = ' ' then NULL else cast(num_pickup as numeric) end as num_pickup,
anio_pickup,
case when num_moto = ' ' then NULL else cast(num_moto as numeric) end as num_moto,
anio_moto,
case when num_bici = ' ' then NULL else cast(num_bici as numeric) end as num_bici,
anio_bici,
case when num_trici = ' ' then NULL else cast(num_trici as numeric) end as num_trici,
anio_trici,
case when num_carret = ' ' then NULL else cast(num_carret as numeric) end as num_carret,
anio_carret,
case when num_canoa = ' ' then NULL else cast(num_canoa as numeric) end as num_canoa,
anio_canoa,
case when num_otro = ' ' then NULL else cast(num_otro as numeric) end as num_otro,
anio_otro,
case when num_ester = ' ' then NULL else cast(num_ester as numeric) end as num_ester,
anio_ester,
case when num_grab = ' ' then NULL else cast(num_grab as numeric) end as num_grab,
anio_grab,
case when num_radio = ' ' then NULL else cast(num_radio as numeric) end as num_radio,
anio_radio,
case when num_tva = ' ' then NULL else cast(num_tva as numeric) end as num_tva,
anio_tva,
case when num_tvd = ' ' then NULL else cast(num_tvd as numeric) end as num_tvd,
anio_tvd,
case when num_dvd = ' ' then NULL else cast(num_dvd as numeric) end as num_dvd,
anio_dvd,
case when num_video = ' ' then NULL else cast(num_video as numeric) end as num_video,
anio_video,
case when num_licua = ' ' then NULL else cast(num_licua as numeric) end as num_licua,
anio_licua,
case when num_tosta = ' ' then NULL else cast(num_tosta as numeric) end as num_tosta,
anio_tosta,
case when num_micro = ' ' then NULL else cast(num_micro as numeric) end as num_micro,
anio_micro,
case when num_refri = ' ' then NULL else cast(num_refri as numeric) end as num_refri,
anio_refri,
case when num_estuf = ' ' then NULL else cast(num_estuf as numeric) end as num_estuf,
anio_estuf,
case when num_lavad = ' ' then NULL else cast(num_lavad as numeric) end as num_lavad,
anio_lavad,
case when num_planc = ' ' then NULL else cast(num_planc as numeric) end as num_planc,
anio_planc,
case when num_maqui = ' ' then NULL else cast(num_maqui as numeric) end as num_maqui,
anio_maqui,
case when num_venti = ' ' then NULL else cast(num_venti as numeric) end as num_venti,
anio_venti,
case when num_aspir = ' ' then NULL else cast(num_aspir as numeric) end as num_aspir,
anio_aspir,
case when num_compu = ' ' then NULL else cast(num_compu as numeric) end as num_compu,
anio_compu,
case when num_impre = ' ' then NULL else cast(num_impre as numeric) end as num_impre,
anio_impre,
case when num_juego = ' ' then NULL else cast(num_juego as numeric) end as num_juego,
anio_juego,
case when tsalud1_h = ' ' then NULL else cast(tsalud1_h as numeric) end as tsalud1_h,
case when tsalud1_m = ' ' then NULL else cast(tsalud1_m as numeric) end as tsalud1_m,
habito_1,
habito_2,
habito_3,
habito_4,
habito_5,
habito_6,
consumo,
nr_viv,
tarjeta,
pagotarjet,
regalotar,
regalodado,
autocons,
regalos,
remunera,
transferen,
parto_g,
embarazo_g,
negcua,
case when est_alim = ' ' then NULL else cast(est_alim as numeric) end as est_alim,
case when est_trans = ' ' then NULL else cast(est_trans as numeric) end as est_trans,
case when factor_hog = ' ' then NULL else cast(factor_hog as numeric) end as factor_hog
from raw.inegi_hogares_2014;
