create table clean.enigh_noagropecuario as
select
folioviv,
foliohog,
numren,
id_trabajo,
tipoact,
numesta,
case when totesta = ' ' then NULL else cast(totesta as numeric) end as totesta,
lugact,
socios,
case when numsocio = ' ' then NULL else cast(numsocio as numeric) end as numsocio,
case when phogar1 = ' ' then NULL else cast(phogar1 as numeric) end as phogar1,
mismop,
mes_2,
mes_3,
mes_4,
mes_5,
mes_6,
case when phogar2 = ' ' then NULL else cast(phogar2 as numeric) end as phogar2,
case when phogar3 = ' ' then NULL else cast(phogar3 as numeric) end as phogar3,
case when phogar4 = ' ' then NULL else cast(phogar4 as numeric) end as phogar4,
case when phogar5 = ' ' then NULL else cast(phogar5 as numeric) end as phogar5,
case when phogar6 = ' ' then NULL else cast(phogar6 as numeric) end as phogar6,
case when t_emp = ' ' then NULL else cast(t_emp as numeric) end as t_emp,
case when h_emp = ' ' then NULL else cast(h_emp as numeric) end as h_emp,
case when m_emp = ' ' then NULL else cast(m_emp as numeric) end as m_emp,
case when t_cpago = ' ' then NULL else cast(t_cpago as numeric) end as t_cpago,
case when h_cpago = ' ' then NULL else cast(h_cpago as numeric) end as h_cpago,
case when m_cpago = ' ' then NULL else cast(m_cpago as numeric) end as m_cpago,
case when t_ispago = ' ' then NULL else cast(t_ispago as numeric) end as t_ispago,
case when h_ispago = ' ' then NULL else cast(h_ispago as numeric) end as h_ispago,
case when m_ispago = ' ' then NULL else cast(m_ispago as numeric) end as m_ispago,
case when t_nispago = ' ' then NULL else cast(t_nispago as numeric) end as t_nispago,
case when h_nispago = ' ' then NULL else cast(h_nispago as numeric) end as h_nispago,
case when m_nispago = ' ' then NULL else cast(m_nispago as numeric) end as m_nispago,
autocons,
case when enproduc = ' ' then NULL else cast(enproduc as numeric) end as enproduc,
case when novend = ' ' then NULL else cast(novend as numeric) end as novend,
case when consinter = ' ' then NULL else cast(consinter as numeric) end as consinter,
peract,
mesact_1,
mesact_2,
mesact_3,
mesact_4,
mesact_5,
mesact_6,
mesact_7,
mesact_8,
mesact_9,
mesact_10,
mesact_11,
mesact_12,
reg_not,
reg_cont,
com_fis,
case when ventas1 = ' ' then NULL else cast(replace(ventas1,',','.') as numeric) end as ventas1,
case when ventas2 = ' ' then NULL else cast(replace(ventas2,',','.') as numeric) end as ventas2,
case when ventas3 = ' ' then NULL else cast(replace(ventas3,',','.') as numeric) end as ventas3,
case when ventas4 = ' ' then NULL else cast(replace(ventas4,',','.') as numeric) end as ventas4,
case when ventas5 = ' ' then NULL else cast(replace(ventas5,',','.') as numeric) end as ventas5,
case when ventas6 = ' ' then NULL else cast(replace(ventas6,',','.') as numeric) end as ventas6,
case when autocons1 = ' ' then NULL else cast(replace(autocons1,',','.') as numeric) end as autocons1,
case when autocons2 = ' ' then NULL else cast(replace(autocons2,',','.') as numeric) end as autocons2,
case when autocons3 = ' ' then NULL else cast(replace(autocons3,',','.') as numeric) end as autocons3,
case when autocons4 = ' ' then NULL else cast(replace(autocons4,',','.') as numeric) end as autocons4,
case when autocons5 = ' ' then NULL else cast(replace(autocons5,',','.') as numeric) end as autocons5,
case when autocons6 = ' ' then NULL else cast(replace(autocons6,',','.') as numeric) end as autocons6,
case when otrosnom1 = ' ' then NULL else cast(replace(otrosnom1,',','.') as numeric) end as otrosnom1,
case when otrosnom2 = ' ' then NULL else cast(replace(otrosnom2,',','.') as numeric) end as otrosnom2,
case when otrosnom3 = ' ' then NULL else cast(replace(otrosnom3,',','.') as numeric) end as otrosnom3,
case when otrosnom4 = ' ' then NULL else cast(replace(otrosnom4,',','.') as numeric) end as otrosnom4,
case when otrosnom5 = ' ' then NULL else cast(replace(otrosnom5,',','.') as numeric) end as otrosnom5,
case when otrosnom6 = ' ' then NULL else cast(replace(otrosnom6,',','.') as numeric) end as otrosnom6,
case when gasneg1 = ' ' then NULL else cast(replace(gasneg1,',','.') as numeric) end as gasneg1,
case when gasneg2 = ' ' then NULL else cast(replace(gasneg2,',','.') as numeric) end as gasneg2,
case when gasneg3 = ' ' then NULL else cast(replace(gasneg3,',','.') as numeric) end as gasneg3,
case when gasneg4 = ' ' then NULL else cast(replace(gasneg4,',','.') as numeric) end as gasneg4,
case when gasneg5 = ' ' then NULL else cast(replace(gasneg5,',','.') as numeric) end as gasneg5,
case when gasneg6 = ' ' then NULL else cast(replace(gasneg6,',','.') as numeric) end as gasneg6,
case when ing1 = ' ' then NULL else cast(replace(ing1,',','.') as numeric) end as ing1,
case when ing2 = ' ' then NULL else cast(replace(ing2,',','.') as numeric) end as ing2,
case when ing3 = ' ' then NULL else cast(replace(ing3,',','.') as numeric) end as ing3,
case when ing4 = ' ' then NULL else cast(replace(ing4,',','.') as numeric) end as ing4,
case when ing5 = ' ' then NULL else cast(replace(ing5,',','.') as numeric) end as ing5,
case when ing6 = ' ' then NULL else cast(replace(ing6,',','.') as numeric) end as ing6,
case when ero1 = ' ' then NULL else cast(replace(ero1,',','.') as numeric) end as ero1,
case when ero2 = ' ' then NULL else cast(replace(ero2,',','.') as numeric) end as ero2,
case when ero3 = ' ' then NULL else cast(replace(ero3,',','.') as numeric) end as ero3,
case when ero4 = ' ' then NULL else cast(replace(ero4,',','.') as numeric) end as ero4,
case when ero5 = ' ' then NULL else cast(replace(ero5,',','.') as numeric) end as ero5,
case when ero6 = ' ' then NULL else cast(replace(ero6,',','.') as numeric) end as ero6,
case when ing_tri = ' ' then NULL else cast(replace(ing_tri,',','.') as numeric) end as ing_tri,
case when ero_tri = ' ' then NULL else cast(replace(ero_tri,',','.') as numeric) end as ero_tri,
case when ventas_tri = ' ' then NULL else cast(replace(ventas_tri,',','.') as numeric) end as ventas_tri,
case when auto_tri = ' ' then NULL else cast(replace(auto_tri,',','.') as numeric) end as auto_tri,
case when otros_tri = ' ' then NULL else cast(replace(otros_tri,',','.') as numeric) end as otros_tri,
case when gasto_tri = ' ' then NULL else cast(replace(gasto_tri,',','.') as numeric) end as gasto_tri
from raw.inegi_noagropecuario_2014;

