create table clean.sifode_int as 
select llave_hogar_h as home_id,
id_mdm_h as family_id,
id_mdm_p as person_id,
c_integrante as family_person_id,
c_con_res as residency_type,
c_cd_parentesco as family_relation,
case when s_tie_curp = ' ' then null else s_tie_curp end as has_curp,
val_nb_renapo as curp_validated_by_renapo,
TO_TIMESTAMP(s_fch_nacimiento, 'MM/DD/YYYY') as date_of_birth,
s_c_cd_edo_nac as state_of_birth_key,
s_c_cd_sexo as gender, 
case when c_cd_edo_civil = ' ' then 'NULL' else c_cd_edo_civil end as marital_status,
s_tipoloc as type_of_locality,
TO_TIMESTAMP(ejercicio, 'YYYY') as fiscal_year_of_survey,
cast(ingreso_pc as numeric) as estimated_income, 
cast(case when pob_lb = '1' then true else false end as boolean) as under_poverty_line,
cast(case when pob_lbm = '1' then true else false end as boolean) as under_minimum_poverty_line,
cast(case when pobreza = '1' then true else false end as boolean) as household_in_poverty,
cast(case when pob_extrem = '1' then true else false end as boolean) as household_in_extreme_poverty,
cast(case when pob_extrem_alim = '1' then true else false end as boolean) as household_in_extreme_poverty_with_food_deprivation,
cast(case when ic_rezedu = ' ' then NULL when ic_rezedu = '1' then true else false end as boolean) as indicator_for_education_deprivation_ic_rezedu,
cast(case when ic_rezedu_3a15 = ' ' then NULL when ic_rezedu_3a15 = '1' then true else false end as boolean) as indicator_for_education_deprivation_ic_rezedu_3a15,
cast(case when ic_rezedu_81 = ' ' then NULL when ic_rezedu_81 = '1' then true else false end as boolean) as indicator_for_education_deprivation_ic_rezedu_81,
cast(case when ic_rezedu_82 = ' ' then NULL when ic_rezedu_82 = '1' then true else false end as boolean) as indicator_for_education_deprivation_ic_rezedu_82,
cast(case when ic_asalud = ' ' then NULL when ic_asalud = '1' then true else false end as boolean) as indicator_for_health_care_deprivation,
cast(case when afil_sp = ' ' then NULL when afil_sp = '1' then true else false end as boolean) as affiliated_with_seguro_popular,
cast(case when afil_imss = ' ' then NULL when afil_imss = '1' then true else false end as boolean) as affiliated_with_imss,
cast(case when afil_issste = ' ' then NULL when afil_issste = '1' then true else false end as boolean) as affiliated_with_issste ,
cast(case when afil_pemex = ' ' then NULL when afil_pemex = '1' then true else false end as boolean) as affiliated_with_pemex_the_navy_or_defense ,
cast(case when afil_privado = ' ' then NULL when afil_privado = '1' then true else false end as boolean) as affiliated_with_a_clinic_or_private_hospital,
cast(case when ic_ss = ' ' then NULL when ic_ss = '1' then true else false end as boolean) as indicator_for_social_security_deprivation,
cast(case when ic_sspob_ocup = ' ' then NULL when ic_sspob_ocup = '1' then true else false end as boolean) as indicator_for_employed_without_social_security_deprivation,
cast(case when ic_sspob_am = ' ' then NULL when ic_sspob_am = '1' then true else false end as boolean) as indicator_for_elders_without_social_security_deprivation,
cast(case when ic_sspob_pnea = ' ' then NULL when ic_sspob_pnea = '1' then true else false end as boolean) as ind_for_non_econ_active_without_soc_security,
cast(case when ic_sspob_otros = ' ' then NULL when ic_sspob_otros = '1' then true else false end as boolean) as indicator_for_other_rubrics_without_social_security,
cast(case when ic_cv1 = ' ' then NULL when ic_cv1 = '1' then true else false end as boolean) as indicator_for_quality_of_dwellings_in_housing_deprivation,
cast(case when icv_pisos1 = ' ' then NULL when icv_pisos1 = '1' then true else false end as boolean) as indicator_for_floor_materials_deprivation,
cast(case when icv_techos1 = ' ' then NULL when icv_techos1 = '1' then true else false end as boolean) as indicator_for_roof_materials_deprivation,
cast(case when icv_muros1 = ' ' then NULL when icv_muros1 = '1' then true else false end as boolean) as indicator_for_wall_materials_deprivation,
cast(case when icv_hac1 = ' ' then NULL when icv_hac1 = '1' then true else false end as boolean) as indicator_for_overcrowding,
cast(case when ic_sbv1 = ' ' then NULL when ic_sbv1 = '1' then true else false end as boolean) as indicator_for_basic_housing_services,
cast(case when isb_agua1 = ' ' then NULL when isb_agua1 = '1' then true else false end as boolean) as indicator_for_access_to_water,
cast(case when isb_dren1 = ' ' then NULL when isb_dren1 = '1' then true else false end as boolean) as indicator_for_drainage_services_deprivation,
cast(case when isb_luz1 = ' ' then NULL when isb_luz1 = '1' then true else false end as boolean) as indicator_for_electricity_services_deprivation,
cast(case when isb_combus1 = ' ' then NULL when isb_combus1 = '1' then true else false end as boolean) as indicator_for_fuel_for_cooking_deprivation,
cast(case when ic_ali1 = ' ' then NULL when ic_ali1 = '1' then true else false end as boolean) as indicator_food_deprivation,
cast(case when seg_alim = ' ' then NULL when seg_alim = '1' then true else false end as boolean) as people_who_are_food_secure,
cast(case when inseg_alim_leve = ' ' then NULL when inseg_alim_leve = '1' then true else false end as boolean) as food_insecurity_light,
cast(case when inseg_alim_moderada = ' ' then NULL when inseg_alim_moderada = '1' then true else false end as boolean) as food_insecurity_moderate,
cast(case when inseg_alim_severa = ' ' then NULL when inseg_alim_severa = '1' then true else false end as boolean) as food_insecurity_sever,
cast(case when discapacidad = ' ' then NULL when discapacidad = '1' then true else false end as boolean) as has_some_disability,
cast(edad_actual as numeric) as actual_age_as_of_16_Dec_2015,
id_unico as sifode_pub_id, 
cast(case when p0116_33 = '1' then true else false end as boolean) as sagarpa_productive_project_2014_p0116_33,  
cast(case when p0116_34 = '1' then true else false end as boolean) as sagarpa_formation_of_social_capital_2014_p0116_34,
cast(case when p0116_115 = '1' then true else false end as boolean) as sagarpa_machinery_and_equipment_p0116_115,
cast(case when p0116_136 = '1' then true else false end as boolean) as sagarpa_rearing_of_animals_p0116_136,
cast(case when p0116_174 = '1' then true else false end as boolean) as sagarpa_fertilizers_p0116_174,
cast(case when p0116_183 = '1' then true else false end as boolean) as sagarpa_infra_tools_primary_prod_p0116_183,
cast(case when p0116_189 = '1' then true else false end as boolean) as sagarpa_costs_for_infrastructure_p0116_189,
cast(case when p0116_195 = '1' then true else false end as boolean) as sagarpa_vegetable_material_or_seeds_p0116_195,
cast(case when p0116_199 = '1' then true else false end as boolean) as sagarpa_works_for_storage_of_water_p0116_199,
cast(case when p0116_207 = '1' then true else false end as boolean) as sagarpa_pesticides_and_agrochemicals_p0116_207,
cast(case when p0116_271 = '1' then true else false end as boolean) as sagarpa_surveys_2014_p0116_271,
cast(case when p0116_273 = '1' then true else false end as boolean) as sagarpa_econ_supt_fina_instru_2014_p0116_273,
cast(case when p0116_274 = '1' then true else false end as boolean) as sagarpa_economic_support_for_studies_2014_p0116_274,
cast(case when p0116_275 = '1' then true else false end as boolean) as sagarpa_program_for_natural_disasters_p0116_275,
cast(case when in_pidr = '1' then true else false end as boolean) as receives_support_sagarpa_in_pidr,
cast(case when p0118_33 = '1' then true else false end as boolean) as sagarpa_productive_project_2014_p0118_33,
cast(case when p0118_34 = '1' then true else false end as boolean) as sagarpa_formation_of_social_capital_2014_p0118_34,
cast(case when p0118_271 = '1' then true else false end as boolean) as sagarpa_surveys_2014_p0118_271,
cast(case when p0118_273 = '1' then true else false end as boolean) as sagarpa_develop_fina_instru_2014_p0118_273,
cast(case when p0118_274 = '1' then true else false end as boolean) as sagarpa_support_for_studies_2014_p0118_274,
cast(case when p0118_275 = '1' then true else false end as boolean) as sagarpa_natural_disasters_p0118_275,
cast(case when in_p0118_2014 = '1' then true else false end as boolean) as receives_support_sagarpa_in_p0118_2014,
cast(case when pimaff_33 = '1' then true else false end as boolean) as sagarpa_corn_beans_productive_project_2014_pimaff_33,
cast(case when p0228_8 = '1' then true else false end as boolean) as sagarpa_training_course_2014_p0228_8,
cast(case when p0034_143 = '1' then true else false end as boolean) as sagarpa_producer_support_2014_p0034_143,
cast(case when procafef_103 = '1' then true else false end as boolean) as sagarpa_cafe_2014_procafef_103,
cast(case when p0136_182 = '1' then true else false end as boolean) as sagarpa_protected_agriculture_2014_p0136_182, 
cast(case when p0132_183 = '1' then true else false end as boolean) as sagarpa_agr_promo_primary_prod_2014_p0132_183,
cast(case when p0131_104 = '1' then true else false end as boolean) as sagarpa_income_of_agricultural_producers_p0131_104,
cast(case when desac_210 = '1' then true else false end as boolean) as sagarpa_fishing_integral_projects_2014_desac_210,
cast(case when p0140_8 = '1' then true else false end as boolean) as sagarpa_fishing_training_course_2014_p0140_8,
cast(case when iner_183 = '1' then true else false end as boolean) as sagarpa_cattle_primary_production_2014_iner_183,
cast(case when propor_234 = '1' then true else false end as boolean) as sagarpa_cattle_incent_catl_prod_2014_propor_234,
cast(case when reprep_136 = '1' then true else false end as boolean) as sagarpa_cattle_rearing_of_animals_2014_reprep_136,
cast(case when mapopef_115 = '1' then true else false end as boolean) as sagarpa_cattle_machinery_and_equipment_2014_mapopef_115,
/*possible duplicate of propor_234*/
cast(case when p0143_234 = '1' then true else false end as boolean) as sagarpa_cattle_incent_catl_prod_2014_p0143_234,
cast(case when p0148_184 = '1' then true else false end as boolean) as sagarpa_agrofood_post_production_2014_p0148_184,
cast(sepo_87 as numeric) as heath_seguro_popular_health_attention_2015_sepo_87,
cast(p0048_4 as numeric) as sct_program_for_temporal_labor_2015,
cast(case when jerft_33 = '1' then true else false end as boolean) as sedatu_young_agricultural_productive_project_2014_jerft_33,
cast(case when s203_278 = '1' then true else false end as boolean) as sedatu_young_rural_school_projects_2015_s203_278,
cast(case when s203_279 = '1' then true else false end as boolean) as sedatu_young_rural_agrobusiness_projects_2015_s203_279,
cast(case when in_s203 = '1' then true else false end as boolean) as receives_support_sedatu_young_rural_2015_in_s203,
cast(case when s048_49 = '1' then true else false end as boolean) as sedatu_program_habitat_pavement_2014_s048_49,
cast(case when s048_50 = '1' then true else false end as boolean) as sedatu_program_habitat_drainage_2014_s048_50,
cast(case when s048_52 = '1' then true else false end as boolean) as sedatu_prog_habiy_net_potbl_water_2014_s048_52,
cast(case when s048_54 = '1' then true else false end as boolean) as sedatu_program_habitat_public_electrification_2014_s048_54,
cast(case when in_s048_h = '1' then true else false end as boolean) as receives_support_sedatu_program_habitat_2014_in_s048_h,
cast(case when pvd_13 = '1' then true else false end as boolean) as sedatu_dignified_housing_tinaco_2014_pvd_13,
cast(case when pvd_16 = '1' then true else false end as boolean) as sedatu_dignified_housing_latrine_2014_pvd_16,
cast(case when pvd_21 = '1' then true else false end as boolean) as sedatu_dignified_housing_solid_flooring_2014_pvd_21,
cast(case when pvd_26 = '1' then true else false end as boolean) as sedatu_dignified_housing_solid_walls_2014_pvd_26,
cast(case when pvd_28 = '1' then true else false end as boolean) as sedatu_dignified_housing_stove_cooker_2014_pvd_28,
cast(case when pvd_48 = '1' then true else false end as boolean) as sedatu_dignified_housing_rural_housing_2014_pvd_48,
cast(case when pvd_61 = '1' then true else false end as boolean) as sedatu_dign_hous_sqrd_mtrs_aplanado_2014_pvd_61,
cast(case when pvd_62 = '1' then true else false end as boolean) as sedatu_dignified_housing_extension_of_housing_2014_pvd_62,
cast(case when pvd_63 = '1' then true else false end as boolean) as sedatu_dign_hous_com_exten_of_hous_2014_pvd_63,
cast(case when pvd_68 = '1' then true else false end as boolean) as sedatu_dignified_housing_electric_installation_2014_pvd_68,
cast(case when pvd_69 = '1' then true else false end as boolean) as sedatu_dignified_housing_hydrolic_installation_2014_pvd_69,
cast(case when pvd_72 = '1' then true else false end as boolean) as sedatu_dignified_housing_laminate_2014_pvd_72,
cast(case when pvd_73 = '1' then true else false end as boolean) as sedatu_dignified_housing_concrete_slab_ceiling_2014_pvd_73,
cast(case when pvd_75 = '1' then true else false end as boolean) as sedatu_dignified_housing_urban_housing_2014_pvd_75,
cast(case when in_pvd = '1' then true else false end as boolean) as receives_sedatu_prog_dign_housing_2014_in_pvd,
cast(case when pvd_13_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_tinaco_2015_pvd_13_2015,
cast(case when pvd_16_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_latrine_2015_pvd_16_2015,
cast(case when pvd_21_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_solid_flooring_2015_pvd_21_2015,
cast(case when pvd_26_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_solid_walls_2015_pvd_26_2015,
cast(case when pvd_28_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_stove_cooker_2015_pvd_28_2015,
cast(case when pvd_48_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_rural_housing_2015_pvd_48_2015,
cast(case when pvd_61_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_aplanado_2015_pvd_61_2015,
cast(case when pvd_62_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_exten_of_hous_2015_pvd_62_2015,
cast(case when pvd_63_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_comb_exten_hous_2015_pvd_63_2015,
cast(case when pvd_68_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_elec_instal_2015_pvd_68_2015,
cast(case when pvd_69_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_hydr_install_2015_pvd_69_2015,
cast(case when pvd_72_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_laminate_2015_pvd_72_2015,
cast(case when pvd_73_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_conc_slab_ceiling_2015_pvd_73_2015,
cast(case when pvd_75_2015 = '1' then true else false end as boolean) as sedatu_dignified_housing_urban_housing_2015_pvd_75_2015,
cast(case when pvd_76_2015 = '1' then true else false end as boolean) as sedatu_dign_hous_sanit_install_2015_pvd_76_2015,
cast(case when in_pvd_2015_h = '1' then true else false end as boolean) as receives_support_sedatu_dignified_housing_2015_in_pvd_2015,
cast(case when pvr_16 = '1' then true else false end as boolean) as sedatu_rural_housing_latrine_2014_pvr_16,
cast(case when pvr_21 = '1' then true else false end as boolean) as sedatu_rural_housing_solid_flooring_2014_pvr_21,
cast(case when pvr_26 = '1' then true else false end as boolean) as sedatu_rural_housing_solid_walls_2014_pvr_26,
cast(case when pvr_28 = '1' then true else false end as boolean) as sedatu_rural_housing_stove_cooker_2014_pvr_28,
cast(case when pvr_48 = '1' then true else false end as boolean) as sedatu_rural_housing_rural_housing_2014_pvr_48,
cast(case when pvr_61 = '1' then true else false end as boolean) as sedatu_rural_housing_aplanado_2014_pvr_61,
cast(case when pvr_62 = '1' then true else false end as boolean) as sedatu_rural_housing_extension_of_housing_2014_pvr_62,
cast(case when pvr_63 = '1' then true else false end as boolean) as sedatu_rural_housing_combined_ext_housing_2014_pvr_63,
cast(case when pvr_72 = '1' then true else false end as boolean) as sedatu_rural_housing_laminate_2014_pvd_7r,
cast(case when pvr_73 = '1' then true else false end as boolean) as sedatu_rural_housing_concrete_slab_ceiling_2014_pvd_7r,
cast(case when in_pvr = '1' then true else false end as boolean) as receives_support_sedatu_rural_housing_2014_in_pvr,
cast(case when pvr_16_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_latrine_2015_pvr_16_2015,
cast(case when pvr_21_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_solid_flooring_2015_pvr_21_2015,
cast(case when pvr_26_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_solid_walls_2015_pvr_26_2015,
cast(case when pvr_28_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_stove_cooker_2015_pvr_28_2015,
cast(case when pvr_48_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_rural_housing_2015_pvr_48_2015,
cast(case when pvr_61_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_aplanado_2015_pvr_61_2015,
cast(case when pvr_62_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_extension_of_housing_2015_pvr_62_2015,
cast(case when pvr_63_2015 = '1' then true else false end as boolean) as sedatu_rur_hous_comb_ext_hous_2015_pvr_63_2015,
cast(case when pvr_72_2015 = '1' then true else false end as boolean) as sedatu_rural_housing_laminate_2015_pvr_72_2015,
cast(case when pvr_73_2015 = '1' then true else false end as boolean) as sedatu_rur_hous_concr_slab_ceil_2015_pvr_73_2015,
cast(case when in_pvr_2015_h = '1' then true else false end as boolean) as receives_support_sedatu_rural_housing_2015_in_pvr_2015,
cast(case when s057_34 = '1' then true else false end as boolean) as sedesol_fonart_social_capital_2014_s057_34,
cast(case when s057_34_2015 = '1' then true else false end as boolean) as sedesol_fonart_social_capital_2015_s057_34_2015,
cast( prosp_27 as numeric) as sedesol_prospera_edu_scholarships_2015_prosp27,
cast( prosp_35 as numeric) as sedesol_prospera_food_support_2015_prosp35,
cast( prosp_36 as numeric) as sedesol_prospera_school_supplies_2015_prosp36,
cast( prosp_37 as numeric) as sedesol_prospera_older_adults_2015_prosp37,
cast( prosp_38 as numeric) as sedesol_prospera_energy_consumption_2015_prosp38,
cast( prosp_39 as numeric) as sedesol_prospera_better_living_2015_prosp39,
cast( prosp_41 as numeric) as sedesol_prospera_children_better_living_2015_prosp41,
cast( in_prosp as numeric) as receives_support_sedesol_prospera_2015_in_prosp,
cast( s065_23 as numeric) as sedesol_paja_eduction_stimulus_2015_s065_23,
cast( s065_43 as numeric) as sedesol_paja_arrival_support_2015_s065_43,
( case when in_paja_2015 = ' ' then 'NULL' else in_paja_2015 end) as receives_support_for_sedesol_paja_2015_in_paja_2015,
cast( s176_37 as numeric) as sedesol_pensions_support_for_seniors_2015_s176_37,
cast( s176_235  as numeric) as sedesol_pensions_pago_de_marcha_2015_s176_235,
cast( s176_236  as numeric) as sedesol_pensions_financial_inclusion_2015_s176_236,
cast( in_s176  as numeric) as receives_support_sedesol_pensions_seniors_2015_in_s176,
cast( pet_4  as numeric) as sedesol_pet_wage_2015_pet_4,
cast( case when pop_33 = '1' then true else false end as boolean) as sedesol_pop_productive_project_2014_pop33,
cast( case when pop_33_2015 = '1' then true else false end as boolean) as sedesol_pop_productive_project_2015_pop33_2015,
cast( case when in_s017_2014 = '1' then true else false end as boolean) as receives_support_se_social_economy_2014_in_s017_2014,
cast( case when s017_33 = '1' then true else false end as boolean) as se_social_economy_productive_project_2015_s017_33,
cast( case when s017_34 = '1' then true else false end as boolean) as se_social_economy_social_capital_2015_s017_34,
cast( case when s017_273 = '1' then true else false end as boolean) as se_social_economy_financial_instruments_2015_s017_273,
cast( case when in_s017_2015 = '1' then true else false end as boolean) as receives_support_se_social_economy_2015_in_s017_2015,
cast( case when s016_280_2014 = '1' then true else false end as boolean) as se_microfin_ruralw_prod_activities_2014_s016_280_2014,
cast( case when s016_280_2015 = '1' then true else false end as boolean) as se_microfin_ruralw_prod_activities_2015_s016_280_2015,
cast( case when s021_280_2014 = '1' then true else false end as boolean) as se_fin_micro_b_prod_activities_2014_s021_280_2014,
cast( case when s021_280_2015 = '1' then true else false end as boolean) as se_fin_micro_b_prod_activities_2021_s016_280_2014,
cast( case when p066_281 = '1' then true else false end as boolean) as se_fund_entrepeneurs_subsidy_2015_p066_281,
cast( case when in_0066_2014 = '1' then true else false end as boolean) as receives_support_se_fund_entrepeneurs_2014_in_0066_2014,
cast( p0170_111 as numeric) as sedesol_community_kitchens_2015_p0170_111,
cast( petsem_4 as numeric ) as semarnat_temporarl_employment_wage_2015_petsem_4,
cast( case when procodesf_33 = '1' then true else false end as boolean) as semarnat_productive_project_2014_procodesf_33,
cast( case when p0110_100 = '1' then true else false end as boolean) as semarnat_wild_life_productive_activities_2014_p0110_100,
cast( case when p0172_233_2014 = '1' then true else false end as boolean) as semarnat_national_forest_program_2014_p0172_233_2014,
cast( case when p0172_233_2015 = '1' then true else false end as boolean) as semarnat_national_forest_program_2015_p0172_233_2015,
cast( case when p0171_233 = '1' then true else false end as boolean) as semarnat_ntl_forest_pro_2014_p0171_233_2014,
cast( paeib_27 as numeric) as cdi_indigineous_2015_paeib_27,
/*are these two duplicates of prosp_35 and prosp39 and prosp_41*/
cast( s118_35 as numeric) as sedesol_food_support_food_2015_s118_35,
cast( s118_39 as numeric) as sedesol_food_support_better_living_2015_s118_39,
cast( s118_41 as numeric) as sedesol_food_support_children2015_s118_41,
cast( in_pal as numeric) as receives_support_sedesol_food_support_2015_in_pal,
cast( s052_2 as numeric) as sedesol_liconsa_social_milk_liter_of_milk_2015_s052_2,
cast( s052_2_h as numeric) as receives_support_sedesol_liconsa_social_milk_2015_s052_2_h,
cast( pei_42 as numeric) as sedesol_working_mothers_child_care_2015_pei_42,
cast( pei_44 as numeric) as sedesol_working_mothers_impulse_2015_pei_44,
cast( pei_47 as numeric) as sedesol_working_mothers_moms_sole_fathers_2015_pei_47,
cast( in_pei as numeric) as receives_support_sedesol_working_mothers_2015_in_pei,
cast( case when p3x1_7 = '1' then true else false end as boolean) as sedesol_3x1_laminate_2014_p3x1_7,
cast( case when p3x1_8 = '1' then true else false end as boolean) as sedesol_3x1_training_course_2014_p3x1_8,
cast( case when p3x1_11 = '1' then true else false end as boolean) as sedesol_3x1_sample_of_water_2014_p3x1_11,
cast( case when p3x1_16 = '1' then true else false end as boolean) as sedesol_3x1_latrine_2014_p3x1_16,
cast( case when p3x1_21 = '1' then true else false end as boolean) as sedesol_3x1_solid_floor_2014_p3x1_21,
cast( case when p3x1_27 = '1' then true else false end as boolean) as sedesol_3x1_scholarship_2014_p3x1_27,
cast( case when p3x1_33 = '1' then true else false end as boolean) as sedesol_3x1_productive_projects_2014_p3x1_33,
cast( case when p3x1_38 = '1' then true else false end as boolean) as sedesol_3x1_energy_consumption_2014_p3x1_38,
cast( case when p3x1_51 = '1' then true else false end as boolean) as sedesol_3x1_drainage_2014_p3x1_51,
cast( case when p3x1_54 = '1' then true else false end as boolean) as sedesol_3x1_public_electrification_2014_p3x1_54,
cast( case when p3x1_73 = '1' then true else false end as boolean) as sedesol_3x1_concrete_slab_ceiling_2014_p3x1_73,
cast( case when p3x1_78 = '1' then true else false end as boolean) as sedesol_3x1_housing_adquisition_2014_p3x1_78,
cast( case when p3x1_80 = '1' then true else false end as boolean) as sedesol_3x1_housing_improvement_2014_p3x1_80,
cast( case when p3x1_174 = '1' then true else false end as boolean) as sedesol_3x1_fertilizers_2014_p3x1_174,
cast( case when p3x1_234 = '1' then true else false end as boolean) as sedesol_3x1cattle_productivity_2014_p3x1_234,
cast( case when in_3x1 = '1' then true else false end as boolean) as receives_support_sedesol_3x1,
cast( case when s216_7 = '1' then true else false end as boolean) as sedesol_priority_zones_laminate_2014_s216_7,
cast( case when s216_11 = '1' then true else false end as boolean) as sedesol_priority_zones_sample_of_water_2014_s216_11,
cast( case when s216_13 = '1' then true else false end as boolean) as sedesol_priority_zones_tinaco_2014_s216_11,
cast( case when s216_15 = '1' then true else false end as boolean) as sedesol_priority_zones_solar_panels_2014_s216_11,
cast( case when s216_16 = '1' then true else false end as boolean) as sedesol_priority_zones_latrine_2014_s216_16,
cast( case when s216_19 = '1' then true else false end as boolean) as sedesol_priority_zones_personal_garden_2014_s216_19,
cast( case when s216_21 = '1' then true else false end as boolean) as sedesol_priority_zones_solid_floor_2014_s216_21,
cast( case when s216_26 = '1' then true else false end as boolean) as sedesol_priority_zones_wall_2014_s216_26,
cast( case when s216_28 = '1' then true else false end as boolean) as sedesol_priority_zones_ecological_stoves_2014_s216_28,
cast( case when s216_50 = '1' then true else false end as boolean) as sedesol_priority_zones_drainage_2014_s216_50,
cast( case when s216_51 = '1' then true else false end as boolean) as sedesol_priority_zones_home_drainage_2014_s216_51,
cast( case when s216_52 = '1' then true else false end as boolean) as sedesol_priority_zones_network_potable_water_2014_s216_52,
cast( case when s216_54 = '1' then true else false end as boolean) as sedesol_priority_zones_public_electrification_2014_s216_54,
cast( case when s216_238 = '1' then true else false end as boolean) as sedesol_priority_zones_additional_room_2014_s216_238,
cast( case when in_pdzp = '1' then true else false end as boolean) as receives_support_for_sedesol,
cast( p0219_264 as numeric) as sep_inea_eductional_services_2015_p0219_264, 
cast( p0220_265 as numeric) as sep_inea_primary_eductional_2015_p0220_265,
cast( p0221_266 as numeric) as sep_inea_secondary_eductional_2015_p0220_266,
cast( case when p0021_232 = '1' then true else false end as boolean) as stps_job_market_service_of_linking_labor_2014_p0021_232,
cast( case when femp_232 = '1' then true else false end as boolean) as stps_job_fairs_service_of_linking_labor_2014_femp_232,
cast( case when p0017_8 = '1' then true else false end as boolean) as stps_employment_support_training_course_2015_p0017_8,
cast( case when p0018_115 = '1' then true else false end as boolean) as stps_employment_machinery_and_equipment_2015_p0018_115,
cast( case when p0019_263 = '1' then true else false end as boolean) as stps_employ_econ_worker_mobil_2015_p0019_263,
cast( case when in_s241_2014 = '1' then true else false end as boolean) as receives_support_sedesol_life_insurance_2014_in_s241_2014,
cast( case when s241_95 = '1' then true else false end as boolean) as sedesol_life_insurance_orphans_2015_s241_95,
cast( case when in_intervenciones = '1' then true else false end as boolean) as  receives_support_individual_level_in_intervenciones,
cast( case when in_intervenciones_h = '1' then true else false end as boolean) as receives_support_household_level_in_intervenciones_h,
cast( case when in_inter_alim = '1' then true else false end as boolean) as  receives_food_prog_individual_level_inter_alim,
cast( case when in_inter_alim_h = '1' then true else false end as boolean) as receives_food_prog_household_level_inter_alim,
TO_TIMESTAMP( case when actualizacion = '0' then '01/01/2015' when actualizacion = '1' then '16/02/2015' when actualizacion = '2' then '09/09/2015' when actualizacion = '3' then '27/10/2015' when actualizacion = '4' then '23/12/2015' else '01/01/1900' end , 'DD/MM/YYYY') as incorporated_into_or_updated_sifode_date,
cast( case when personas_m = '1' then true else false end as boolean ) as person_found_in_more_than_one_household, 
cast( case when hogares_m = '1' then true else false end as boolean ) as household_with_persons_found_in_other_households,
cast( case when estatus_hogar = ' ' then '-99999' else estatus_hogar end as numeric ) as house_status,
cast( case when p_total = ' ' then '-99999' else p_total end as numeric) as p_total
from raw.sifode_int;
